spring:
  datasource:
    master:
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      jdbcUrl: jdbc:mysql://192.168.1.230:3306/db1?useUnicode=true&nullCatalogMeansCurrent=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
    slave:
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      jdbcUrl: jdbc:mysql://192.168.1.230:3306/db2?useUnicode=true&nullCatalogMeansCurrent=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root